import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    en: {
        //Participant log in
        logIn:"Log in",
        groupID:"Group ID",
        SUBMIT:"SUBMIT",
        signInAsOwner:"Sign in as a group owner",
        //Group owner sign in
        signIn:"Sign In",
        eMail:"E-mail",
        passwd:"Password",
        SIGN_IN:"SIGN IN",
        forgorPasswd:"Forgot password?",
        noGroupCreaterAcc:"Don't have a group-creater account?",
        signInAsParticipant:"Sign in as Participant",
        //Group owner sigh up
        sighUp:"SIGN UP",
        SIGN_UP:"SIGN UP",
        //Group owner page (left side)
        myGroups:"My groups",
        pendQuests:"Pending quests",
        settings:"Settings",
        help:"Help",
        logOut:"Log out",
        //My groups
        yourGroups:"Your Groups",
        groupNameChange:"Group name changing",
        groupName:"Group Name",
        CANCEL:"CANCEL",
        SAVE:"SAVE",
        createNewGroup:"CREATE NEW GROUP",
        newGroupCreate:"Creating a new group",
        CREATE:"CREATE",
        //Group owner page (right side)
        members:"MEMBERS",
        quests_owner:"QUESTS",
        leaderboard:"LEADERBOARD",
        chooseGroup:"Choose a group",
        noMembers:"You have no members yet",
        //Add member
        addMember:"Add Member",
        name:"Name",
        ADD:"ADD",
        //Delete member
        deleteMember:"Delete Member",
        doUWantToDelete:"Do you want to delete {0} from this group?",
        DELETE:"DELETE",
        //Quests
        quest:"Quest",
        description:"Description",
        expectAnswer:"Expected answer",
        addNewSubquest:"ADD NEW SUBQUEST",
        //Edit quest
        editQuest:"Edit Quest",
        title:"Title",
        EDIT:"EDIT",
        //Edit subquest
        editSubquest:"Edit subquest",
        typeOfVarification:"Choose type of varification",
        type:"Type",
        none:"None",
        text:"Text",
        image:"Image",
        enterDescription:"Enter description",
        //Create quest
        createNewQuest:"Creating a new quest",
        //Pending quests
        memberAnswer:"Member's answer",
        CONFIRM:"CONFIRM",
        noPendingQuests:"You have no pending quests yet",
        //Settings
        accSettings:"Account Settings",
        changeAvatar:"CHANGE AVATAR",
        newPasswd:"New Password",
        repeatPasswd:"Repeat new password",
        generalSettings:"General Settings",
        language:"Language",
        SAVE_CHANGES:"SAVE CHANGES",
        //Participant page (left side)
        me:"Me",
        quests_participant:"Quests",
        group:"Group",
        //Me 
        DELETE_MY_ACCOUNT:"DELETE MY ACCOUNT",
        //Quests 
        progress:"Progress",
        subquest:"Subquest",
        answer:"Answer",
        LOG_OUT:"LOG OUT"
    },
    ru: {
        logIn:"Авторизация",
        groupID:"ID группы",
        SUBMIT:"ПОДТВЕРДИТЬ",
        signInAsOwner:"Войти как владелец группы",
        signIn:"Вход",
        eMail:"Почта",
        passwd:"Пароль",
        SIGN_IN:"ВОЙТИ",
        forgorPasswd:"Забыли пароль?",
        noGroupCreaterAcc:"У Вас нету учетной записи создателя группы?",
        signInAsParticipant:"Войти как участник",
        sighUp:"РЕГИСТАРЦИЯ",
        SIGN_UP:"ЗАРЕГИСТРИРОВАТЬСЯ",
        myGroups:"Мои группы",
        pendQuests:"Квесты, ожидающие подтверждения",
        settings:"Настройки",
        help:"Помощь",
        logOut:"Выход",
        yourGroups:"Ваши группы",
        groupNameChange:"Изменение названия группы",
        groupName:"Название группы",
        CANCEL:"ОТМЕНИТЬ",
        SAVE:"СОХРАНИТЬ",
        createNewGroup:"СОЗДАТЬ НОВУЮ ГРУППУ",
        newGroupCreate:"Создание новой группы",
        CREATE:"СОЗДАТЬ",
        members:"УЧАСТНИКИ",
        quests:"КВЕСТЫ",
        leaderboard:"ТАБЛИЦА ЛИДЕРОВ",
        chooseGroup:"Выберите группу",
        noMembers:"У Вас ещё нету участников",
        addMember:"Добавление участника",
        name:"Имя",
        ADD:"ДОБАВИТЬ",
        deleteMember:"Удаление участника",
        doUWantToDelete:"Вы уверенны, что хотите удалить участника {0} из этой группы?",
        DELETE:"УДАЛИТЬ",
        quest:"Квест",
        description:"Описание",
        expectAnswer:"Ожидаемый ответ",
        addNewSubquest:"ДОБАВИТЬ НОВЫЙ ПОДКВЕСТ",
        editQuest:"Редактирование квеста",
        title:"Название",
        EDIT:"РЕДАКТИРОВАТЬ",
        editSubquest:"Редактирование подквеста",
        typeOfVarification:"Виберите тип подтверждения",
        type:"Тип",
        none:"Ничего",
        text:"Текст",
        image:"Картинка",
        enterDescription:"Введите описание подквеста",
        createNewQuest:"Создание нового квеста",
        memberAnswer:"Ответ участника",
        CONFIRM:"ПОДТВЕРДИТЬ",
        noPendingQuests:"У Вас ещё нету квестов, которые ожидают ответа",
        accSettings:"Настройки учётной записи",
        changeAvatar:"ИЗМЕНИТЬ ФОТО",
        newPasswd:"Новый пароль",
        repeatPasswd:"Введите новый пароль ещё раз",
        generalSettings:"Общие настройки",
        language:"Язык",
        SAVE_CHANGES:"СОХРАНИТЬ ИЗМЕНЕНИЯ",
        me:"Я",
        quests_participant:"Квесты",
        group:"Группа",
        DELETE_MY_ACCOUNT:"УДАЛИТЬ УЧЁТНУЮ ЗАПИСЬ",
        progress:"Прогресс",
        subquest:"Подквест",
        answer:"Ответ",
        LOG_OUT:"Выход"
    },
    ua: {
        logIn:"Авторизація",
        groupID:"ID групи",
        SUBMIT:"ПІДТВЕРДИТИ",
        signInAsOwner:"Увійти як власник групи",
        signIn:"Вхід",
        eMail:"Пошта",
        passwd:"Пароль",
        SIGN_IN:"УВІЙТИ",
        forgorPasswd:"Забули пароль?",
        noGroupCreaterAcc:"У Вас немає облікового запису творця групи?",
        signInAsParticipant:"Увійти як учасник",
        sighUp:"РЕЄСТРАЦІЯ",
        SIGN_UP:"ЗАРЕЄСТРУВАТИСЬ",
        myGroups:"Мої групи",
        pendQuests:"Квести, які очікують на підтвердження",
        settings:"Налаштування",
        help:"Допомога",
        logOut:"Вихід",
        yourGroups:"Ваші групи",
        groupNameChange:"Зміна назви групи",
        groupName:"Назва групи",
        CANCEL:"ВІДМІНИТИ",
        SAVE:"ЗБЕРЕГТИ",
        createNewGroup:"СТВОРИТИ НОВУ ГРУПУ",
        newGroupCreate:"Створення нової групи",
        CREATE:"СТВОРИТИ",
        members:"УЧАСНИКИ",
        quests:"КВЕСТИ",
        leaderboard:"ТАБЛИЦЯ ЛІДЕРІВ",
        chooseGroup:"Виберіть групу",
        noMembers:"У Вас поки немає учасників",
        addMember:"Додавання учасника",
        name:"Ім'я",
        ADD:"ДОДАТИ",
        deleteMember:"Видалення учасника",
        doUWantToDelete:"Ви впевнені, що хочете видалити учасника {0} із цієї групи?",
        DELETE:"ВИДАЛИТИ",
        quest:"Квест",
        description:"Опис",
        expectAnswer:"Очікувана відповідь",
        addNewSubquest:"ДОДАТИ НОВИЙ ПІДКВЕСТ",
        editQuest:"Редагування квеста",
        title:"Назва",
        EDIT:"РЕДАГУВАТИ",
        editSubquest:"Редагування підквеста",
        typeOfVarification:"Виберіть тип підтверджения",
        type:"Тип",
        none:"Нічого",
        text:"Текст",
        image:"Картинка",
        enterDescription:"Введіть опис підквеста",
        createNewQuest:"Створення нового квеста",
        memberAnswer:"Відповідь учасника",
        CONFIRM:"ПІДТВЕРДИТИ",
        noPendingQuests:"У Вас ще немає квестів, які очікують на відповідь",
        accSettings:"Налаштування облікового запису",
        changeAvatar:"ЗМІНИТИ ФОТО",
        newPasswd:"Новий пароль",
        repeatPasswd:"Введіть новий пароль ще раз",
        generalSettings:"Загальні налаштування",
        language:"Мова",
        SAVE_CHANGES:"ЗБЕРЕГТИ ЗМІНИ",
        me:"Я",
        quests_participant:"Квести",
        group:"Група",
        DELETE_MY_ACCOUNT:"ВИДАЛИТИ ОБЛІКОВИЙ ЗАПИС",
        progress:"Прогрес",
        subquest:"Підквест",
        answer:"Відповідь",
        LOG_OUT:"Вихід"
    }
   });
